### ISSUE TITLE
Implement/fix tests

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-test-selectors#1]
The repo has some tests but they don't run successfully. Also I'm not sure how this would be tested - I guess we would like to compile and render a template and assert that no `data-test-*` attributes are included in the rendered markup.

Also the mocha jshint test seems to hang. Or maybe it checks the `node_modules` folder as well causing it to take very long which makes it appear to be hanging.

**Comment by pangratz** [comment]
I have this mostly done, will commit tomorrow. hype :steam_locomotive: on the way.

**Comment by marcoow** [comment]
🚄

**Comment by marcoow** [comment]
Ideally we would also have this set up so that it runs against the template compiler that ships with Ember 1.13.x, the current release, beta and canary.
