### ISSUE TITLE
Data Test Attribute Not Always Appearing When Specified

### ISSUE THREAD

**Issue by zamoore** [simplabs/ember-test-selectors#103]
When I try to add a data-test attribute to an element, it doesn't appear on the element in the test build unless assigning it a value of "true".

For example:

### This does not work
```handlebars
<h2 class="summary-name" data-test-campaign-summary-name>{{campaign.name}}</h2>
```

### This does work
```handlebars
<h2 class="summary-name" data-test-campaign-summary-name="true">{{campaign.name}}</h2>
```

### Using the following versions:
Ember: 2.12.1
Ember Data: 2.12.2
jQuery: 3.2.1
Ember Simple Auth: 1.2.2
Model Fragments: 2.11.2

**Comment by marcoow** [comment]
Hm, this is working fine for us with Ember 2.11. Might be a regression with 2.12…

**Comment by Turbo87** [comment]
@zamoore we had been using Ember 2.12 here until this morning too, so I don't think that the Ember version is the problem. Unfortunately without some way to reproduce your issue this is hard to fix. Do you have a project somewhere that you can share that shows this issue?

**Comment by tomlagier** [comment]
We are encountering a similar issue on Ember 2.13

**Comment by marcoow** [comment]
@zamoore, @tomlagier: as @Turbo87 said above, would be awesome if you could link to a project that shows the error (or create an example project that does).

**Comment by fusion2004** [comment]
I work with @zamoore, and we do not have a reproduction app currently. I am worried that it may be hard to make one because what we've found is that when it does occur, restarting the computer seems to fix it. `rm -rf`ing node_modules, bower_components, tmp, & dist directories doesn't seem to help.

What could we do once we have a computer start running into the issue to try and help identify what is going on?

**Comment by Turbo87** [comment]
> restarting the computer seems to fix it

@rwjblue @stefanpenner any clue what could be causing something like that?

**Comment by astronomersiva** [comment]
> restarting the computer seems to fix it

`npm cache clean` is also fixing it. We have also encountered situations where test selectors are stripped while running tests if the tag is inside an if...else block. For example,

```
{{#if  condition}}
      <div data-test-title="does-not-appear">...</div>
{{else}}
      <div data-test-title="does-not-appear">...</div>
{{/if}}
```

However, if the if...else block is enclosed in another tag containing a data-test attribute, they are not stripped.

**Comment by graemechapman** [comment]
I have just encountered this on Ember 2.13, I tried restarting, `npm cache clean`, `yarn cache clean`, and deleting temp files, local and global node modules, none of these fixed the issue. 

What fixed it for me was reverting to an old commit from before we started using ember-test-selectors, running tests, and then updating back to master.

**Comment by fusion2004** [comment]
I'd also like to note that we don't see this issue in CI, which would seem to indicate that it only happens when trying to run tests multiple times, possibly related to making changes to the ember app you are running tests on, as well.

At this point, I'm grasping because of my lack of knowledge involving the intricacies of running tests & building ember apps. Is there something about running tests or building an ember app that may involve temp files outside of the project directory?

**Comment by fusion2004** [comment]
Ah-ha! I may have a clue!

Curious enough to attempt to answer my own question, I used DTrace to see what files were being opened during building & running tests and I saw it working with files in a folder named "if-you-need-to-delete-this-open-an-issue-async-disk-cache". In the same directory, I also found several folders starting with "testem-" in their name. I deleted all of them, and then, my test build worked!

When it happens again, I'll be more selective and delete folders one-at-a-time until the tests pass & report back.

**Comment by Turbo87** [comment]
@rwjblue @stefanpenner ☝️  any ideas?

**Comment by fusion2004** [comment]
I have confirmed with my coworker @bjbatten that when this issue starts occurring, deleting the "if-you-need-to-delete-this-open-an-issue-async-disk-cache" directory seems to resolve it.

**Comment by bgentry** [comment]
I was also having this issue, and clearing out my `$TMPDIR/if-you-need-to-delete-this-open-an-issue-async-disk-cache` got the attrs to start appearing again.

Ember v2.13.0, latest version of this addon.

**Comment by Turbo87** [comment]
Since clearing the async cache appears to fix the issue I'm expecting https://github.com/simplabs/ember-test-selectors/pull/128 to have resolved it too. Please let use know if you still have any issues with the current release.
