### ISSUE TITLE
tagName warning on custom component reopen

### ISSUE THREAD

**Issue by blimmer** [simplabs/ember-test-selectors#106]
I write a custom mixin that I apply on in test runs to automatically bind a property to all components so I can easily test to see if a given component is rendered.

Imagine I have a component `foo-bar`, this logic automatically binds `data-test-component='foo-bar'` to the attributes. However, because I reopen Ember.Component to get this behavior, I automatically get this behavior with components without tagNames.

Because of this [new(ish) warning](https://github.com/simplabs/ember-test-selectors/blob/master/addon/utils/bind-data-test-attributes.js#L20-L27) I get a lot of warning output in my console.

I used to be able to do this check myself:

```js
  init() {
    // you can't bind attributes to tagless components
    if (this.tagName !== '') {
      const dataTestAttr = ['data-test-component'];
      this.attributeBindings = this.attributeBindings ? this.attributeBindings.concat(dataTestAttr) : dataTestAttr;
    }

    this._super(...arguments);
  },
```

but now this doesn't work. Is there a workaround I could use to get this working again?

**Comment by blimmer** [comment]
Here's my `tests/test-helper.js` file, showing what I'm doing exactly now (2.13.x) and how I'm working around this warning for now.

```
import Ember from 'ember';
import resolver from './helpers/resolver';
import {
  setResolver
} from 'ember-qunit';
import { start } from 'ember-cli-qunit';

setResolver(resolver);

// There has got to be a better way!
// https://github.com/simplabs/ember-test-selectors/issues/106
let realEmberWarn = Ember.warn;
Ember.warn = function(_1, _2, opts) {
  if (Ember.get(opts, 'id') !== "ember-test-selectors.empty-tag-name") {
    realEmberWarn(...arguments);
  }
}
let ComponentTestingMixin = Ember.Mixin.create({
  'data-test-component': Ember.computed(function() {
    let [, componentName] = this._debugContainerKey.replace(/\//g, '-').split(':');
    return Ember.String.dasherize(componentName);
  })
});
Ember.Component.reopen(ComponentTestingMixin);

start();
```

**Comment by marcoow** [comment]
I think the best way to hide this warning would be to use [`registerWarnHandler`](https://emberjs.com/api/classes/Ember.Debug.html#method_registerWarnHandler)?

**Comment by Turbo87** [comment]
@blimmer I don't understand. Why do you bind `data-test-component` on a tagless component? and actually in your first snippet it looks like you only bind it on non-tagless components. but since the warning only triggers for tagless components with `data-test-*` attributes it shouldn't be triggered for you. can you maybe provide a more complete reproduction of this?

**Comment by blimmer** [comment]
I definitely don't want to bind it on tagless components, but the presence of the `data-test-component` attribute in that reopen seems to cause the problem.

You can see an example here:

https://github.com/blimmer/ember-raffle/tree/ember-test-selectors/issue-106

https://travis-ci.org/blimmer/ember-raffle/builds/228331241#L412

```
        Log: |
            { type: 'warn',
              text: '\'WARNING: ember-test-selectors could not bind data-test-* properties on <raffle@component:liquid-outlet::ember1773> automatically because tagName is empty.\'\n' }
            { type: 'warn',
              text: '\'WARNING: ember-test-selectors could not bind data-test-* properties on <raffle@component:-lf-get-outlet-state::ember1774> automatically because tagName is empty.\'\n' }
            { type: 'warn',
              text: '\'WARNING: ember-test-selectors could not bind data-test-* properties on <raffle@component:liquid-bind::ember1775> automatically because tagName is empty.\'\n' }
            { type: 'warn',
              text: '\'WARNING: ember-test-selectors could not bind data-test-* properties on <raffle@component:liquid-versions::ember1777> automatically because tagName is empty.\'\n' }
```

If we can figure out a solution for this, I'd be happy to generalize this and open a PR. It's a very handy way to delegate most testing of a component to its integration test, and simply make sure it's rendered in an acceptance test.

https://github.com/blimmer/ember-raffle/blob/ember-test-selectors/issue-106/tests/acceptance/raffles-test.js#L26

**Comment by blimmer** [comment]
If anyone's looking to do this with the new Ember modules, here's how you do it:

```javascript
import { registerWarnHandler } from '@ember/debug';

registerWarnHandler((_1, opts, next) => {
  if (get(opts, 'id') !== "ember-test-selectors.empty-tag-name") {
    next(...arguments);
  }
});
```

**Comment by Turbo87** [comment]
@blimmer I just looked at this again as https://github.com/simplabs/ember-test-selectors/pull/205 changed the warning to an assertion. I've opened https://github.com/simplabs/ember-test-selectors/pull/261, which adds a test explaining how to accomplish what I think it is you're doing.

**Comment by blimmer** [comment]
Thanks @Turbo87 . Yep, this works as I expect: https://github.com/blimmer/ember-raffle/commit/6dc758e93bcb2de2fec4ca659b32d3de9fe634e3
