### ISSUE TITLE
I still see test selectors in production files

### ISSUE THREAD

**Issue by dossorio** [simplabs/ember-test-selectors#118]
Hi ! first of all thanks for the great addon! It makes testing markup agnostic which is something I love! <3

I had a look to the production build though, and I could still see some test selectors in there, so I put together this [repo](https://github.com/dossorio/ember-test-selectors-issue) so you can reproduce the issue.

Steps to reproduce:
- Run `ember build --prod`
- Have a look in the files that were generated, you will be able to see the `data-test-component` there

Is this intended ? I was expecting the test selector not to be there right ?

Thanks !

**Comment by marcoow** [comment]
I confirmed the test selector is still present. Any idea @Turbo87 ?
