### ISSUE TITLE
Explore API for child selecting

### ISSUE THREAD

**Issue by kellyselden** [simplabs/ember-test-selectors#121]
I have some code like so:

```js
  click(
    testSelector('primitive-list-header') + ' '
      + testSelector('pointer')
  );
```

Thoughts about how this could get better?

**Comment by Turbo87** [comment]
just brainstorming, but what about something like this:

```js
import { ts } from 'ember-test-selectors';

click(ts`@primitive-list-header .foo @pointer=3`);
```

which would be transformed at runtime to:

```js
click('[data-test-primitive-list-header] .foo [data-test-pointer="3"]');
```

I'm open to other suggestions about the prefix symbol (`@`), but in general this seems like a concise API that could work.

**Comment by chriskrycho** [comment]
I like the use of a template string and 👍 to the API idea in general. My only concern with `@` is that it maps to Glimmer binding syntax and might introduce some confusion there for people new to it. Most any symbol will overload *something*; my concern is just that that one seems extra likely to confuse.

Maybe even just bracketing it? Might be a nice overlap with the actually-generated selector.

```js
click(ts`[primitive-list-header] .foo [pointer=3]`);
```

**Comment by joukevandermaas** [comment]
`ts` reminds me of TypeScript, so I had to read the snippets twice before I knew what was going on :smile:

Anyway, I have quite some helper functions like this:

```
function selectItem(number) {
    click(`[data-test-item="$number"]`);
}
```

So it would be nice if that kind of use-case would continue to work with the `ts` template function.

**Comment by kellyselden** [comment]
@Turbo87 I like the template string and the escaping.

**Comment by Turbo87** [comment]
given that `@` already has a meaning in CSS (and also in Glimmer) I'm leaning towards using `%` as a prefix:

```
click(ts`%primitive-list-header .foo %pointer=3`);
```

**Comment by marcoow** [comment]
see https://github.com/simplabs/ember-test-selectors/pull/122#issuecomment-315179386 - the more I think about this the less I understand why we all seem to feel the best API for this case is not actually

```
click('[data-test-primitive-list-header] .foo [data-test-pointer=3]');
```

Yes, this is a few more characters but it's also much clearer as it simply uses the actual selector instead of going through a bunch of hoops only to save a few characters.

**Comment by kellyselden** [comment]
I think I agree with @marcoow

**Comment by caseywatts** [comment]
On my team, we started pulling test selectors up into a simple object at the top of test files:
https://gist.github.com/caseywatts/46643c9c0825c5e8b1e2542b0a150659
