### ISSUE TITLE
Add smoke tests

### ISSUE THREAD

**Issue by pangratz** [simplabs/ember-test-selectors#13]
using [ember-cli-addon-tests](https://github.com/tomdale/ember-cli-addon-tests)

**Comment by marcoow** [comment]
👍

**Comment by Turbo87** [comment]
@pangratz do the existing tests now qualify as smoke tests?

**Comment by pangratz** [comment]
@Turbo87 what I meant back then with the exceptional descriptive "add smoke tests" were tests, which check that the result of `ember build` doesn't contain `data-test-*` anymore in the templates (and in JS too if #10 is done).

I guess it's related to #28.

Feel free to close this one in favour of #28.

**Comment by Turbo87** [comment]
@pangratz well, right now we're not stripping *everything* out, so the tests you describe would always fail. I'd propose to implement those tests in the PR that finally strips out all the things.

**Comment by marcoow** [comment]
Closing this as we have pretty good coverage now
