### ISSUE TITLE
data-test selectors for components without assigning values

### ISSUE THREAD

**Issue by matthias-k** [simplabs/ember-test-selectors#136]
Hi,

I tried using data-test-selectors in a component as

    {{my-component data-test-my-component}}

however, this breaks the template. Maybe this is a limitation of handlebars, then this would not be fixable, but then it might be helpful to have a comment in the README. If this is actually possible, it would be very convenient, since right now I have to use something like

    {{my-component data-test-my-component="1"}}

which looks not as clean.

**Comment by marcoow** [comment]
That is indeed a limitation of Handlebars but one that is supposed to be overcome by https://github.com/simplabs/ember-test-selectors/blob/master/transform-test-selector-params-to-hash-pairs.js. Which versions of Ember and Ember CLI are you on?

**Comment by matthias-k** [comment]
a pretty outdated version: Ember 2.9.0, Ember CLI 2.9.1. I guess this is one more reason to finally upgrade to the latest version again and try to stick to the release cycle ;).

**Comment by marcoow** [comment]
It should work correctly though. Can you try cleaning your repo?

**Comment by matthias-k** [comment]
What exactly do you mean by "cleaning my repo"?

**Comment by marcoow** [comment]
`git clean -dfx && npm install && bower install`

**Comment by matthias-k** [comment]
This didn't help. I'm now even using ember-cli 2.15.0 and ember-test-selectors 0.3.7 and the error persists.
```
Parse error on line 2:
...e data-test-selected}}  <label data-tes
-----------------------^
Expecting 'EQUALS', got 'CLOSE'
```

**Comment by Turbo87** [comment]
> Maybe this is a limitation of handlebars

yes, the limitation is that if you use `data-test-my-component` without any value if needs to be written before any attributes that do have a value. we have a comment about this in the README now (see https://github.com/simplabs/ember-test-selectors#usage-in-components)

**Comment by matthias-k** [comment]
Great, thanks for your help!
