### ISSUE TITLE
Deprecate TransformTestSelectorParamsToHashPairs transform

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-test-selectors#151]
As discussed in #149 doesn't work reliably in all supported version of Ember, if it breaks results in very cryptic error messages and is really a small convenience feature anyway as you can always do

```hbs
{{foo-component data-test-foo=true}}
```

instead of

```hbs
{{foo-component data-test-foo}}
```

anyway.

**Comment by Turbo87** [comment]
@marcoow as discovered in #150 it does actually work all the way down to Ember 1.11, but the other arguments RE usability still stand.

**Comment by marcoow** [comment]
I think this is similar to the `testSelector` helper that we had - it adds complexity for very little value.

**Comment by Turbo87** [comment]
as mentioned in https://github.com/ember-codemods/ember-no-implicit-this-codemod/pull/51#issuecomment-565707076, we should write a small codemod, deprecate the pattern and then throw it away.

with angle bracket syntax there is no need for this hack anymore 🎉

**Comment by Turbo87** [comment]
https://github.com/simplabs/ember-test-selectors-params-codemod ✨

**Comment by runspired** [comment]
hit this because of the no-implicit-this codemod, +1 for deprecating and was happy it was an easy fix.
