### ISSUE TITLE
Incoming private API breakage

### ISSUE THREAD

**Issue by ef4** [simplabs/ember-test-selectors#159]
Accessing anything on a `ComputedProperty` instance is private API and is likely to break in the future (possibly the very soon future). This addon is accessing `isDescriptor`:

https://github.com/simplabs/ember-test-selectors/blob/master/addon/utils/bind-data-test-attributes.js#L30

The tl;dr is that everybody wants to make `Ember.get` optional and just use real ES5 getters for computed properties. As soon as we do that, `component.attributeBindings` will stop giving you a `ComputedProperty` instance with an `isDescriptor`, and would always return the value directly, even when it is implemented as computed property.

**Comment by Turbo87** [comment]
@ef4 any idea how we can figure out if `attributeBindings` is writable within that code?

**Comment by ef4** [comment]
It seems that this code just warns and gives up when it can't write to attrributeBindings, so perhaps you can just try to `set` and catch the error if it's a computed property without a setter, so as to convert the error into a pleasant warning.

**Comment by Turbo87** [comment]
guess I'll wait until this code actually breaks in canary and then we'll see how to fix/work around it

**Comment by ef4** [comment]
Yeah, that's reasonable. The relevant RFC is https://github.com/emberjs/rfcs/pull/281

**Comment by Gaurav0** [comment]
This issue is causing a test to fail in https://github.com/simplabs/ember-test-selectors/pull/172

**Comment by Turbo87** [comment]
indeed, I'm just surprised that it works without issues in one of our apps that is running 3.0 🤔

**Comment by ef4** [comment]
It will only break if you happen to have attributesBindings as a computed property. It's not a common thing to do.
