### ISSUE TITLE
incorporating new modules API

### ISSUE THREAD

**Issue by gokatz** [simplabs/ember-test-selectors#166]
Just noticed ember version of `ember-test-selectors` has been updated to ember version 2.16 and also incorporated modules import. Since we haven't included any polyfill in the addon, consuming application may break if they relatively pull out the npm version using ^ or ~. Can we add a [polyfill](https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill)?

**Comment by Turbo87** [comment]
That polyfill is already included via ember-cli-babel :)

**Comment by gokatz** [comment]
sorry for the trouble!
