### ISSUE TITLE
Possible mistake in documentation of data-attribute?

### ISSUE THREAD

**Issue by Fryie** [simplabs/ember-test-selectors#20]
[In this section](https://github.com/simplabs/ember-test-selectors#selectors-based-on-data-attributes), we first introduce `data-test-selector="post-title"`, but in the next example this becomes `data-test-post-title`. Is this a leftover from an older version (which I think it is, judging from the [change history](https://github.com/simplabs/ember-test-selectors/commit/9aceff6aef4d0ce23755a99c83e7a50f15e04de8)) or am I missing some piece?

I can make a PR for it, but I just wanted to make sure I'm not mistaken first.

**Comment by pangratz** [comment]
Good catch! A PR is very welcome!

Can you also update the sentence in this section from `… makes sure to remove all these data attributes in the …` to `… makes sure to remove all these data-test-* attributes in the …`

Cheers.
