### ISSUE TITLE
Incorrectly ignores `0` as a value

### ISSUE THREAD

**Issue by chriskrycho** [simplabs/ember-test-selectors#23]
To reproduce:

```js
testSelector('foo', 0);
```

The expected value is `[data-test-foo="0"]`. The actual value is `[data-test-foo]`.

Workaround: convert to a string:

```js
testSelector('foo', `${0}`);
```

---

I ran into this because I have a small helper that wraps this and passes in an ID, so:

```js
mySelector = id => testSelector('foo', id);
```

This works normally, *unless* the `id` is 0.

**Comment by marcoow** [comment]
Thanks for reporting - should be pretty easy to fix if you (or anyone) wants to submit a PR.
