### ISSUE TITLE
Data attributes as computed properties should support setting attributes on HTML element (angle bracket component invocation syntax)

### ISSUE THREAD

**Issue by jelhan** [simplabs/ember-test-selectors#279]
Ember-test-selectors should support passing data attributes defined as computed property on component using `...attributes` spread syntax. Currently it does not.

Having a component like this:

```js
// app/components/my-component.js
export default Ember.Component({
  tagName: '',
  'data-test-ping': 'pong'
});
```

```hbs
// app/templates/components/my-component.hbs
<p ...attributes>
  some content
</p>
```

I would expect this output:

```html
<p data-test-ping="pong">
  some content
</p>
```

But it throws an assertion: `ember-test-selectors could not bind data-test-* properties on <ember-test-selectors@component:my-component::ember176> automatically because tagName is empty.`

If component defines a wrapper tag it does not throw but shows confusing behavior. Assuming we have the same component as above but with `tagName: 'div'`, invoking the component like this `<MyComponent data-test-foo />` will render:

```html
<div data-test-ping="pong" data-test-foo>
  <p data-test-foo>
    some content
  </p>
</div>
```

**Comment by marcoow** [comment]
I'm closing this - I'd say the solution @Turbo87 suggests is an improvement over defining the `data-test-` attribute in the component's JS anyway.

**Comment by jelhan** [comment]
@marcoow Could you please add some more details, why this won't be fixed? IMO this addon is behaving very strange if used together with new syntax. One use case described in readme isn't working at all, another one is adding the test selector twice. I think at least readme should be updated to take angle-bracket component invocation syntax into account.

**Comment by marcoow** [comment]
> another one is adding the test selector twice.

in which scenario specifically does this happen?

See my comment [here](https://github.com/simplabs/ember-test-selectors/issues/267#issuecomment-446957275) for a longer explanation on why we won't add this and why I think defining `data-test-` attributes in a component's JS is not something that should usually be done anyway.

**Comment by jelhan** [comment]
> If component defines a wrapper tag it does not throw but shows confusing behavior. Assuming we have the same component as above but with tagName: 'div', invoking the component like this <MyComponent data-test-foo /> will render:
> 
> ```
> <div data-test-ping="pong" data-test-foo>
>   <p data-test-foo>
>     some content
>   </p>
> </div>
> ```

https://ember-twiddle.com/e837b4473e6c1668fc942778324a32bb?openFiles=templates.application.hbs%2Ctemplates.components.my-component.hbs

**Comment by marcoow** [comment]
That same thing is true for e.g. `class` though: https://ember-twiddle.com/ba1cb304040edfd9772ed154c1dfd31e?openFiles=templates.application.hbs%2Ctemplates.components.my-component.hbs

```hbs
<div data-test-ping="pong" data-test-foo class="ember-view test">
  <p data-test-foo class="test">
    some content
  </p>
</div>
```

To me, that seems to indicate it's not a good idea to use `...attributes` for components that don't set `tagName: ''` but not a problem that is specific to ETS.
