### ISSUE TITLE
Check if production build uses `data-test-` attributes

### ISSUE THREAD

**Issue by pangratz** [simplabs/ember-test-selectors#28]
It would be cool if we could check the production build of the JS code for `data-test-` strings, because this would mean that `data-test-` selectors are used though they are stripped.

**Comment by marcoow** [comment]
Ideally we'd error-out then and show a message.

**Comment by marcoow** [comment]
Closing this as discussed. This would cover an error case that came up in discussions we had on the topic but we don't actually know whether it'd ever happen for anyone anyway. If people actually do run into problems with production code relying on `data-test-*` attributes we can also reopen this and add the sanity check later on.
