### ISSUE TITLE
Can't apply selector to `link-to` in helper form

### ISSUE THREAD

**Issue by allthesignals** [simplabs/ember-test-selectors#314]
I can't seem to apply a test selector to the inline form of `link-to`:

`{{link-to 'Features' 'features' data-test-header-features-link="features"}}`

`link-to`, a component, appears to be using positional params. According to docs, this should work: 

`{{link-to data-test-header-features-link 'Features' 'features'}}`

This throws:

`Error: Assertion Failed: You attempted to define a `{{link-to "Features"}}` but did not pass the parameters required for generating its dynamic segments. There is no route named Features`

I've tried it a few other ways with no luck. It seems to just either not show or throw some error about a missing route (because it's trying to use data-test as an input). 

I'm on Ember 3.6. How do most people use test selectors for links?

**Comment by Turbo87** [comment]
@allthesignals I've tried to reproduce your problem but it seems to be working fine for me. I've opened a PR to add a test case for `link-to` components to our test suite (https://github.com/simplabs/ember-test-selectors/pull/315) and that also seems to be working fine 🤔

**Comment by allthesignals** [comment]
Woops! I made a silly mistake. Sorry to waste your time @Turbo87!
