### ISSUE TITLE
Replace "environments" option with "strip" option

### ISSUE THREAD

**Issue by Turbo87** [simplabs/ember-test-selectors#41]
I'd like to propose replacing our current [`environment` option](https://github.com/simplabs/ember-test-selectors#options) with a simple boolean `strip` option.

This option should default to the opposite of the [`tests` property](https://github.com/ember-cli/ember-cli/blob/v2.10.0/lib/broccoli/ember-app.js#L156) of the `EmberApp` instance, which is `true` when either `ember test` was used or when we're not in production mode.

To recreate the old behavior you'd simply have to set `strip` to `EmberApp.env() === 'production'`.

/cc @marcoow @pangratz

**Comment by Turbo87** [comment]
The `tests` property is currently not documented properly and not officially public API, but I'm pretty confident that we will change this when we document it.

see https://github.com/ember-cli/ember-cli/issues/6656

**Comment by marcoow** [comment]
> This option should default to the opposite of the tests property of the EmberApp instance, which is true when either ember test was used or when we're not in production mode.

Yeah, that's probable fine.

> The tests property is currently not documented properly and not officially public API, but I'm pretty confident that we will change this when we document it.

Maybe we should hold off for now then as this is also a breaking change on our side?

**Comment by Turbo87** [comment]
> Maybe we should hold off for now then as this is also a breaking change on our side?

This is a breaking change, yes.

`tests` is already used in several official addons though, so the possibility of it not being considered public is very low:

- [ember-cli-mocha](https://github.com/ember-cli/ember-cli-mocha/blob/master/index.js#L152)
- [ember-cli-chai](https://github.com/ember-cli/ember-cli-chai/blob/master/index.js#L120)

**Comment by pangratz** [comment]
Seems good to me!
