### ISSUE TITLE
attributeBindings not being initialized in components on integration tests

### ISSUE THREAD

**Issue by bgentry** [simplabs/ember-test-selectors#49]
I'm seeing an issue when trying to get my app upgraded to v0.1.0. Unfortunately I haven't been able to create a reproduction yet or locate the exact source of this issue yet. What I'm running into is this:

I have a component invocation which includes a `data-test-*` input attribute. When I view my app in dev, the attribute is bound correctly. It's also being set correctly in acceptance tests. On integration tests for my components, however, the `data-test-*` attributes are not being bound at all. Using the following initializer in my component, I was able to confirm that the attribute is indeed set correctly but `attributeBindings` is `undefined`:

```js
  init() {
    this._super(...arguments);
    debugger;
  },
```

The component itself is really very simple:

```js
const ValidatedFormGroupComponent = Component.extend({
  changeset: null,
  propertyName: null,

  classNames: ['form-group'],
  
  // ... some computed properties
});

ValidatedFormGroupComponent.reopenClass({
  positionalParams: ['changeset', 'propertyName']
});

export default ValidatedFormGroupComponent;
```

I have to run for now but I'm hoping to be able to put together a proper reproduction later today. I tried creating tests to trigger this inside the dummy app but was unable to do so. No idea what might be different about my app's testing setup that could cause this.

**Comment by marcoow** [comment]
Oh my, you're right - the initializer that we use to setup the auto-binding never runs for integration tests, at least not automatically 😞 

This is something that was simply overlooked and should certainly be fixed until 1.0.

**Comment by Turbo87** [comment]
that is indeed true, initializers only run in acceptance tests. I have to admit that I'm not sure *how* to fix this though. any ideas?

an alternative is exposing a mixin or component subclass instead of the initializer, but that will obviously not be a drop-in replacement.

**Comment by bgentry** [comment]
#50 should take care of this. Please try it out and lmk!

**Comment by simonihmig** [comment]
As a long time user of this addon (congrats to the new version, really great effort there!), we used a custom mixin for all our components. While it did not do data bindings in production builds, the mixin was still there in the inheritance chain. So still having this feels a bit like a step backwards with all the effort to not affect production builds in this new version.

So the approach of @bgentry in his PR makes sense to me! Would love to make the switch soon when this is sorted out, thanks again for the hard work everybody! 👏
