### ISSUE TITLE
test-data-* does not work when "tagName: ''" inside a component

### ISSUE THREAD

**Issue by jackmatt2** [simplabs/ember-test-selectors#51]
Unfortunately the automatic attribute binding of `data-test-*` does not work when `tagName=''` in a component such as [ember-power-select](https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select.js)

**Comment by marcoow** [comment]
Yes, in that case there's nothing to bind the attribute to actually. I don't think there's anything reasonable we could do in this case.

**Comment by Turbo87** [comment]
@jackmatt2 can you explain what you expect to happen when setting `data-test-*` attributes on a component that uses `tagName: ''`?

**Comment by jackmatt2** [comment]
It would be good if it got added to the first DOM element produced by the component.  This would normally be a `div` or something in a `.hbs` template.  Only issue here being a use case for a tagless component with no `.hbs`.

**Comment by marcoow** [comment]
> It would be good if it got added to the first DOM element produced by the component. 

I don't think we should do that to be honest. I also think it would be impossible to even find that element as there's no parent element that we could scope the selector to.

**Comment by Turbo87** [comment]
@jackmatt2 what if the component has multiple tags in the template? why would you only add the selector to the first one?

IMHO if you wanted to have a selector around a tagless component then you should probably put a `<span>` or `<div>` around the component and assign the `data-test-*` attributes on the wrapper instead.

**Comment by jackmatt2** [comment]
@Turbo87  Yeah, I was considering that too. I think this probably makes sense.  The only ugly bit about this solution is that you need to know ahead of time which components are tagless and which are not.  If you are using third party libraries you don't normally want to get into the dirty details of how the component is generated.  I have another possible solution, if `data-test-*` is added to a tagless component, it is automatically wrapped in a `div` by default (actual tag could be controlled by `data-test-tagName`).

```
{{my-tagless-component data-test-tagName="span" data-test-id="Helllo World"}}
```

Might produce

```
<span data-test-id="Hello World">
  ... tagless template rendered here
</span>
```

This was you can consistently add `data-test-*` to all component and know it will always work.

**Comment by marcoow** [comment]
That would actually change the component's rendered HTML though which would likely result in display errors when we strip the `data-test-*` attributes in production and the component doesn't get wrapped in the extra `div` or `span`.

I think what we should probably do is log a warning like _"You're trying to bind a data-test-* attribute to a tagless component. The attribute will not be bound actually as there is no tag to bind it to."_.

**Comment by jackmatt2** [comment]
@marcoow sounds good.
