### ISSUE TITLE
No documentation for how to disable empty tagName assertion

### ISSUE THREAD

**Issue by elwayman02** [simplabs/ember-test-selectors#571]
There is an assertion that causes test failures if you apply a test selector to a component with an empty tagname. The assertion claims to link to documentation for how to disable the assertion, but it links to documentation that doesn't exist:

https://github.com/simplabs/ember-test-selectors/blob/master/addon/utils/bind-data-test-attributes.js#L26

How do we *actually* disable this assertion?

**Comment by Turbo87** [comment]
it's right above it: https://github.com/simplabs/ember-test-selectors/blob/c91ca9ad4013d531404baed0fe9d31effe5ddc48/addon/utils/bind-data-test-attributes.js#L20. you need to set `supportsDataTestProperties: true` on the component, though I'd generally advise against using `data-test` **properties** on components these days and just use `...attributes` instead to apply them

**Comment by elwayman02** [comment]
Yea, I found it but it's undocumented and the assertion needs to be updated. :)

I wish we could use splattributes, but we're still living the classic life over here so we need to maintain support until we get all the features we need enabled.

**Comment by Turbo87** [comment]
since the automatic binding on components is deprecated now, we can probably close this issue since it won't be addressed anymore before the code is finally removed.
