### ISSUE TITLE
6.x does not work with Embroider

### ISSUE THREAD

**Issue by mydea** [simplabs/ember-test-selectors#769]
Just leaving this here as a reference issue if somebody else runs into this - since 6.x dropped the bind-data-test-attributes util, embroider will break as it has a custom adapter which references this. I made a PR fixing this in embroider:

https://github.com/embroider-build/embroider/pull/904

**Comment by Turbo87** [comment]
looks like https://github.com/embroider-build/embroider/pull/904 was merged so I'll close this issue :)
