### ISSUE TITLE
Deprecation use of Reopening the Ember.Component super class

### ISSUE THREAD

**Issue by makannew** [simplabs/ember-test-selectors#780]
Bellow deprecation warning appears on console:

"Reopening the Ember.Component super class itself is deprecated. Consider alternatives such as installing event listeners on the document or add the customizations to specific subclasses. [deprecation id: ember.component.reopen]"

**Comment by Turbo87** [comment]
see https://github.com/simplabs/ember-test-selectors/issues/709, this has been fixed in v5.3.0 with a config option, and fully fixed in v6.0.0
