### ISSUE TITLE
Add template helpers for attaching test selectors to elements

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-test-selectors#9]
It might be helpful to have sth. that automatically attaches test selectors to elements, e.g. `<h1 {{test-selector="post-title"}}>…</h1>` (which would result in `<h1 data-test-selector="post-title">…</h1>`). That might even support passing a model which could be used to automatically create a test selector based on the model's type and id: `<div {{test-selector post}}>…</div>` (which would result in `<div data-test-selector="post-1">…</div>`).

**Comment by clekstro** [comment]
I'd like this as well, but it appears that that syntax isn't currently supported. There's currently an open [RFC](https://github.com/mixonic/rfcs/blob/element-modifier/text/0111-element-modifier.md), not sure if/when that will land though.

**Comment by marcoow** [comment]
It seems to be supported in general though as you could do `<div {{action 'some'}}>bla</div>` for example.

**Comment by clekstro** [comment]
Yeah, it's only disabled for a subset of cases, in this case for helpers.  I'm not sure which version it was introduced in off the top of my head, but this is the current output:

```js
Uncaught Error: Assertion Failed: Helpers may not be used in the element form, 
for example <div {{my-helper}}>.
```

**Comment by marcoow** [comment]
I don't think this is necessary anymore. It's pretty straight forward to add test selectors like

```hbs
<div data-test-selector="{{post.id}}">…</div>
```

or

```hbs
{{my-component resource=post data-test-resource=post.id}}
```

etc. now. I also think these are a little easier to understand and maintain than the helper approach (`<div {{test-selector post}}>`) suggested above.

@clekstro: do you think this is still needed?

**Comment by clekstro** [comment]
I don't think so. 

I originally thought this was the easiest way to approach "removal" of the attributes by having some environment-based check within the helper to decide whether to emit the attribute or not, but the current approach to parse/prune the AST at build time seems 👌 .

**Comment by marcoow** [comment]
👌
