### ISSUE TITLE
Discussion: ability to not strip test-selectors in addon builds?

### ISSUE THREAD

**Issue by lukemelia** [simplabs/ember-test-selectors#95]
Here's our situation: we are extracting an addon out of app. The tests for this app use ember-test-selectors. Once extracted to an addon, though, the same tests do not pass because when the addon builds, test selectors are stripped.

It would seem to be a inarguably good thing to allow addon authors to use ember-test-selectors to test their addons.

In addition, I would like to propose that apps be able to not strip test selectors when building their addon for tests, either by default or by configuration.

Thoughts? Is this already possible and I am missing it?

**Comment by Turbo87** [comment]
@lukemelia have you seen https://github.com/simplabs/ember-test-selectors#configuration? I'm not sure if that covers your use case?

**Comment by lukemelia** [comment]
@Turbo87 In an addon that configuration affects the dummy app, but not the addon/ build

**Comment by Turbo87** [comment]
I'm not sure I'm following. Do you have an example repo somewhere that I can take a look at?

**Comment by lukemelia** [comment]
@Turbo87 I just pushed a simple example app here: https://github.com/lukemelia/ets-addon-example, including a failing test that demonstrates the issue.

**Comment by Turbo87** [comment]
@lukemelia haven't forgotten about you, just haven't found the time yet, sorry 😞
